name: maverick
description: Lua for Flutter
version: 0.1.0
homepage: https://github.com/mars3142/maverick

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^4.1.2

flutter:
  plugin:
    platforms:
      android:
        package: org.mars3142.maverick
        pluginClass: MaverickPlugin
      ios:
        pluginClass: MaverickPlugin

ffigen:
  name: Lua5
  description: Lua 5.1.5 bindings
  output: 'lib/bindings/lua.g.dart'
  headers:
    entry-points:
      - 'ios/Classes/lua/lapi.h'
      - 'ios/Classes/lua/lauxlib.h'
      - 'ios/Classes/lua/lcode.h'
      - 'ios/Classes/lua/ldo.h'
      - 'ios/Classes/lua/lfunc.h'
      - 'ios/Classes/lua/lua.h'
  comments:
    style: any
    length: full
